NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations.
2. Faster Operations.


In [1]:
import numpy as np

List vs Numpy - Time taken


In [2]:
from time import process_time

Time taken by list

In [6]:
python_list = [i for i in range(15000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)      #process_time


0.0007934120000001599


In [7]:
np_array = np.array([i for i in range(15000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.0004657969999994904


Numpy Arrays

In [8]:
#list
l1 = [1,2,3,4,5]
print(l1)
print(type(l1))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#Creating a one-dimensional array
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [12]:
a.shape

(6,)

In [18]:
#Creating a two-dimensional array
b = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)])
print(b)
print(type(b))
b.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
<class 'numpy.ndarray'>


(4, 4)

In [20]:
c = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)],dtype = float)
print(c)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


Initial Placeholders in Numpy arrays

In [21]:
#create a numpy array of zeros
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#create a numpy array of ones

y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
#create a numpy array of particular value
t = np.full((4,5),6)
print(t)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [25]:
#create of identity matrix
p = np.eye(4)
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
#create a numpy array with random values
h = np.random.random((3,4))
print(h)

[[0.10633445 0.12596683 0.18978604 0.86084328]
 [0.33178866 0.67186668 0.1472506  0.12235652]
 [0.09558082 0.42963631 0.10408641 0.83085993]]


In [29]:
#create a numpy array with integer values
e = np.random.randint(20,80,(3,4))
print(e)

[[24 40 74 35]
 [50 29 43 35]
 [24 41 23 40]]


In [32]:
#create a numpy array of evenly spaced ---> specifying the number of values required for us
y = np.linspace(20,90,3)
print(y)

[20. 55. 90.]


In [34]:
#create a numpy array of evenly spaced ---> specifying the step
f = np.arange(20,90,4)
print(f)

[20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88]


In [36]:
#convert a list into a numpy array
l2 = [10,20,30,40,50]
np_array = np.asarray(l2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


Analyzing a numpy array

In [39]:
s = np.random.randint(20,100,(5,5))
print(s)


[[88 33 34 86 55]
 [71 96 74 70 71]
 [95 35 44 69 23]
 [73 97 33 89 29]
 [73 60 78 65 43]]


In [40]:
#array dimension
s.shape

(5, 5)

In [41]:
#number of dimensions
s.ndim

2

In [42]:
#number of elements in the numpy array
s.size

25

In [43]:
#check the datatype of the elements in the numpy array
s.dtype

dtype('int64')

Mathematical operations on numpy array

In [44]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

print(l1 + l2)      #concatinate the two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [52]:
a = np.random.randint(10,100,(3,3))
b = np.random.randint(20,50,(3,3))
print(a)
print(b)

[[22 92 89]
 [54 67 83]
 [28 51 10]]
[[35 47 20]
 [41 42 34]
 [28 41 44]]


In [53]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[ 57 139 109]
 [ 95 109 117]
 [ 56  92  54]]
[[-13  45  69]
 [ 13  25  49]
 [  0  10 -34]]
[[ 770 4324 1780]
 [2214 2814 2822]
 [ 784 2091  440]]
[[0.62857143 1.95744681 4.45      ]
 [1.31707317 1.5952381  2.44117647]
 [1.         1.24390244 0.22727273]]


In [54]:
a = np.random.randint(10,100,(3,3))
b = np.random.randint(20,50,(3,3))
print(a)
print(b)

[[50 14 11]
 [25 48 20]
 [56 90 81]]
[[40 33 21]
 [37 48 38]
 [22 36 27]]


In [56]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 90  47  32]
 [ 62  96  58]
 [ 78 126 108]]
[[ 10 -19 -10]
 [-12   0 -18]
 [ 34  54  54]]
[[2000  462  231]
 [ 925 2304  760]
 [1232 3240 2187]]
[[1.25       0.42424242 0.52380952]
 [0.67567568 1.         0.52631579]
 [2.54545455 2.5        3.        ]]


Array Manipulation

In [57]:
a = np.random.randint(20,40,(2,4))
print(a)
a.shape

[[25 22 20 35]
 [21 30 33 25]]


(2, 4)

In [60]:
#transpose of the above array
trans = np.transpose(a)
print(trans)
trans.shape

[[25 21]
 [22 30]
 [20 33]
 [35 25]]


(4, 2)

In [62]:
#another way of transposing
trans2 = a.T
print(trans2)
trans2.shape

[[25 21]
 [22 30]
 [20 33]
 [35 25]]


(4, 2)

In [63]:
#reshaping array
a = np.random.randint(20,40,(2,4))
print(a)
a.shape

[[28 32 27 31]
 [26 23 22 39]]


(2, 4)

In [65]:
b = a.reshape(4,2)
print(b)
b.shape

[[28 32]
 [27 31]
 [26 23]
 [22 39]]


(4, 2)